# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03-ngame-training-pipeline.ipynb.

# %% auto 0
__all__ = ['block', 'args', 'metric', 'model', 'learn']

# %% ../nbs/03-ngame-training-pipeline.ipynb 4
import os,torch
from xcai.basics import *
from xcai.models.MMM00X import DBT009,DBT010

# %% ../nbs/03-ngame-training-pipeline.ipynb 5
os.environ['WANDB_MODE'] = 'disabled'

# %% ../nbs/03-ngame-training-pipeline.ipynb 6
block = XCBlock.from_cfg('data', valid_pct=0.001, tfm='ng', tokenizer='sentence-transformers/msmarco-distilbert-base-v4')

# %% ../nbs/03-ngame-training-pipeline.ipynb 7
args = XCLearningArguments(
    output_dir='/scratch/scai/phd/aiz218323/Projects/xc_nlg/outputs/03-NGAME-training-pipeline',
    logging_first_step=True,
    per_device_train_batch_size=1024,
    per_device_eval_batch_size=64,
    representation_num_beams=200,
    representation_accumulation_steps=100,
    save_strategy="steps",
    evaluation_strategy='steps',
    eval_steps=1000,
    save_steps=1000,
    save_total_limit=5,
    num_train_epochs=50,
    predict_with_representation=True,
    label_names=['plbl2data_idx', 'plbl2data_data2ptr'],
    target_indices_key='plbl2data_idx',
    target_pointer_key='plbl2data_data2ptr',
    adam_epsilon=1e-6,
    warmup_steps=100,
    weight_decay=0.01,
    learning_rate=2e-3,
)

# %% ../nbs/03-ngame-training-pipeline.ipynb 8
metric = PrecRecl(block.n_lbl, block.test.data_lbl_filterer, prop=block.train.dset.data.data_lbl,
                  pk=10, rk=200, rep_pk=[1, 3, 5, 10], rep_rk=[10, 100, 200])

# %% ../nbs/03-ngame-training-pipeline.ipynb 9
model = DBT010.from_pretrained('sentence-transformers/msmarco-distilbert-base-v4', apply_softmax=True)

# %% ../nbs/03-ngame-training-pipeline.ipynb 10
learn = XCLearner(
    model=model,
    args=args,
    train_dataset=block.train.dset,
    eval_dataset=block.test.dset,
    data_collator=block.collator,
    compute_metrics=metric,
)

# %% ../nbs/03-ngame-training-pipeline.ipynb 11
learn.train()
