# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04-metadata-augmented-trie-for-distilbert.ipynb.

# %% auto 0
__all__ = ['block', 'mname', 'model', 'args', 'metric', 'learn', 'a_trie', 'o']

# %% ../nbs/04-metadata-augmented-trie-for-distilbert.ipynb 2
import os, pandas as pd, warnings, torch
from tqdm.auto import tqdm
from scipy import stats

from xcai.basics import *
from xcai.models.MMM00X import DBT007, DBT008

# %% ../nbs/04-metadata-augmented-trie-for-distilbert.ipynb 3
os.environ['WANDB_MODE'] = 'disabled'

# %% ../nbs/04-metadata-augmented-trie-for-distilbert.ipynb 4
block = XCBlock.from_cfg('data_meta', valid_pct=0.001, tokz='distilbert-base-uncased')

# %% ../nbs/04-metadata-augmented-trie-for-distilbert.ipynb 7
mname = '/scratch/scai/phd/aiz218323/Projects/xc_nlg/outputs/04-metadata-augmented-trie-for-distilbert/distilbert-base-uncased_RB33-NAR-1+8-2_(mapped)LF-WikiSeeAlsoTitles-320K/checkpoint-168000'
model = DBT007.from_pretrained(mname, tn_targ=10_000, ig_tok=0)

# %% ../nbs/04-metadata-augmented-trie-for-distilbert.ipynb 8
args = XCLearningArguments(
    output_dir='/scratch/scai/phd/aiz218323/Projects/xc_nlg/outputs/04-metadata-augmented-trie-for-distilbert/distilbert-base-uncased_RB33-NAR-1+8-2_(mapped)LF-WikiSeeAlsoTitles-320K',
    generation_length_penalty=1.5,
    per_device_eval_batch_size=64,
    evaluation_strategy='steps',
    label_names=['lbl2data_idx'],
)

# %% ../nbs/04-metadata-augmented-trie-for-distilbert.ipynb 10
metric = PrecRecl(block.n_lbl, block.test.data_lbl_filterer, prop=block.train.dset.data.data_lbl,
                  pk=10, rk=200, rep_pk=[1, 3, 5, 10], rep_rk=[2, 3, 10, 50, 100, 200])

# %% ../nbs/04-metadata-augmented-trie-for-distilbert.ipynb 11
learn = XCLearner(
    model=model, 
    args=args,
    data_collator=block.collator, 
    compute_metrics=metric,
)

# %% ../nbs/04-metadata-augmented-trie-for-distilbert.ipynb 20
a_trie = XCTrie.from_block(block, meta=['hlk'])

# %% ../nbs/04-metadata-augmented-trie-for-distilbert.ipynb 21
learn.tbs.trie = a_trie

# %% ../nbs/04-metadata-augmented-trie-for-distilbert.ipynb 22
learn.tbs.n_bm = learn.args.generation_num_beams = 20

# %% ../nbs/04-metadata-augmented-trie-for-distilbert.ipynb 23
o = learn.predict(block.test.dset)
print(o.metrics)

#display_metric(o.metrics)

# %% ../nbs/04-metadata-augmented-trie-for-distilbert.ipynb 25
# torch.save(o, f'{mname}/predictions/test_lbl_atrie-hlk_n-smp-2000_seed-50.pth')
torch.save(o, f'{mname}/predictions/test_lbl_atrie-hlk.pth')
