# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05-metadata-augmented-input-and-trie-for-distilbert.ipynb.

# %% auto 0
__all__ = ['dump_dir', 'mname', 'model', 'args', 'metric', 'learn', 'trie', 'o']

# %% ../nbs/05-metadata-augmented-input-and-trie-for-distilbert.ipynb 2
import os, pandas as pd, warnings, torch, pickle
from tqdm.auto import tqdm
from scipy import stats

from xcai.basics import *
from xcai.models.MMM00X import DBT007, DBT008
from xcai.transform import AugmentMetaInputIdsTfm

# %% ../nbs/05-metadata-augmented-input-and-trie-for-distilbert.ipynb 3
os.environ['WANDB_MODE'] = 'disabled'

# %% ../nbs/05-metadata-augmented-input-and-trie-for-distilbert.ipynb 4
dump_dir = '/scratch/scai/phd/aiz218323/Projects/xc_nlg/outputs/05-metadata-augmented-input-and-trie-for-distilbert/'

# %% ../nbs/05-metadata-augmented-input-and-trie-for-distilbert.ipynb 11
with open(f'{dump_dir}/data/block.pkl', 'rb') as f: block, test_dset = pickle.load(f)

# %% ../nbs/05-metadata-augmented-input-and-trie-for-distilbert.ipynb 13
mname = f'{dump_dir}/distilbert-base-uncased_RB33-NAR-3+8-2_(mapped)LF-WikiSeeAlsoTitles-320K/checkpoint-190000'
model = DBT007.from_pretrained(mname, tn_targ=10_000, ig_tok=0)

# %% ../nbs/05-metadata-augmented-input-and-trie-for-distilbert.ipynb 14
args = XCLearningArguments(
    output_dir=f'{dump_dir}/distilbert-base-uncased_RB33-NAR-3+8-2_(mapped)LF-WikiSeeAlsoTitles-320K',
    generation_length_penalty=1.5,
    per_device_eval_batch_size=16,
    evaluation_strategy='steps',
    label_names=['lbl2data_idx'],
)

# %% ../nbs/05-metadata-augmented-input-and-trie-for-distilbert.ipynb 15
metric = PrecRecl(test_dset.n_lbl, test_dset.data.data_lbl_filterer, prop=block.train.dset.data.data_lbl,
                  pk=10, rk=200, rep_pk=[1, 3, 5, 10], rep_rk=[2, 3, 10, 50, 100, 200])

# %% ../nbs/05-metadata-augmented-input-and-trie-for-distilbert.ipynb 17
learn = XCLearner(
    model=model, 
    args=args,
    data_collator=block.collator, 
    compute_metrics=metric,
)

# %% ../nbs/05-metadata-augmented-input-and-trie-for-distilbert.ipynb 19
trie = XCTrie.from_block(block)

# %% ../nbs/05-metadata-augmented-input-and-trie-for-distilbert.ipynb 20
learn.tbs.trie = trie

# %% ../nbs/05-metadata-augmented-input-and-trie-for-distilbert.ipynb 21
learn.tbs.n_bm = learn.args.generation_num_beams = 10
# learn.tbs.n_bm = learn.args.generation_num_beams = 200

# %% ../nbs/05-metadata-augmented-input-and-trie-for-distilbert.ipynb 24
o = learn.predict(test_dset)
display_metric(o.metrics)

torch.save(o, f'{mname}/predictions/test_lbl_n-bm-200_n-smp-2000_seed-50.pth')
