# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/09-anshul-trie-implementation.ipynb.

# %% auto 0
__all__ = ['dump_dir', 'mname', 'model', 'args', 'test_dset', 'metric', 'learn']

# %% ../nbs/09-anshul-trie-implementation.ipynb 2
import os, pandas as pd, warnings, torch, pickle, numpy as np
from typing import Dict, Optional, List
from tqdm.auto import tqdm
from scipy import stats
import scipy.sparse as sp
import torch.nn.functional as F
from itertools import chain

from xcai.basics import *
from xcai.models.MMM00X import DBT007, DBT008, BT0002
from xcai.transform import AugmentMetaInputIdsTfm

# %% ../nbs/09-anshul-trie-implementation.ipynb 3
os.environ['WANDB_MODE'] = 'disabled'

# %% ../nbs/09-anshul-trie-implementation.ipynb 7
dump_dir = '/scratch/scai/phd/aiz218323/Projects/xc_nlg/outputs/09-anshul-trie-implementation/'

# %% ../nbs/09-anshul-trie-implementation.ipynb 9
mname = f'/home/aiscuser/scratch/Projects/XC-NLG/models/distilbert-base-uncased_RB33-NAR-1+8-2_(mapped)LF-WikiSeeAlsoTitles-320K/checkpoint-168000'
model = DBT007.from_pretrained(mname, tn_targ=10_000, ig_tok=0)

# %% ../nbs/09-anshul-trie-implementation.ipynb 11
args = XCLearningArguments(
    output_dir=f'{dump_dir}/distilbert-base-uncased_RB33-NAR-1+8-2_(mapped)LF-WikiSeeAlsoTitles-320K',
    generation_length_penalty=0.0,
    per_device_eval_batch_size=64,
    evaluation_strategy='steps',
    label_names=['lbl2data_idx'],
)

# %% ../nbs/09-anshul-trie-implementation.ipynb 12
test_dset = block.test.dset.sample(n=1000, seed=50)

# %% ../nbs/09-anshul-trie-implementation.ipynb 13
metric = PrecRecl(test_dset.n_lbl, test_dset.data.data_lbl_filterer, prop=block.train.dset.data.data_lbl,
                  pk=10, rk=200, rep_pk=[1, 3, 5, 10], rep_rk=[2, 3, 10, 50, 100, 200])

# %% ../nbs/09-anshul-trie-implementation.ipynb 14
learn = XCLearner(
    model=model, 
    args=args,
    data_collator=block.collator, 
    compute_metrics=metric,
)
