# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/13-metadata-trie-for-distilbert.ipynb.

# %% auto 0
__all__ = ['dump_dir', 'fname', 'mname', 'model', 'args', 'learn', 'meta_toks', 'meta_info', 'trie']

# %% ../nbs/13-metadata-trie-for-distilbert.ipynb 2
import os, pandas as pd, warnings, torch, pickle, numpy as np
from tqdm.auto import tqdm
from scipy import stats

import xclib.utils.sparse as xs

from xcai.basics import *
from xcai.models.MMM00X import DBT007, DBT008
from xcai.transform import AugmentMetaInputIdsTfm

# %% ../nbs/13-metadata-trie-for-distilbert.ipynb 3
os.environ['WANDB_MODE'] = 'disabled'

# %% ../nbs/13-metadata-trie-for-distilbert.ipynb 4
dump_dir = '/scratch/scai/phd/aiz218323/Projects/xc_nlg/outputs/13-metadata-trie-for-distilbert'

# %% ../nbs/13-metadata-trie-for-distilbert.ipynb 5
fname = '/scratch/scai/phd/aiz218323/Projects/xc_nlg/outputs/05-metadata-augmented-input-and-trie-for-distilbert/data/block.pkl'
with open(fname, 'rb') as f: block, test_dset = pickle.load(f)

# %% ../nbs/13-metadata-trie-for-distilbert.ipynb 7
mname = f'/scratch/scai/phd/aiz218323/Projects/xc_nlg/outputs/05-metadata-augmented-input-and-trie-for-distilbert/distilbert-base-uncased_RB33-NAR-3+8-2_(mapped)LF-WikiSeeAlsoTitles-320K/checkpoint-190000'
model = DBT007.from_pretrained(mname, tn_targ=10_000, ig_tok=0)

# %% ../nbs/13-metadata-trie-for-distilbert.ipynb 8
args = XCLearningArguments(
    output_dir=f'{dump_dir}/distilbert-base-uncased_RB33-NAR-3+8-2_(mapped)LF-WikiSeeAlsoTitles-320K',
    generation_length_penalty=1.5,
    per_device_eval_batch_size=32,
    evaluation_strategy='steps',
    label_names=['lbl2data_idx'],
)

# %% ../nbs/13-metadata-trie-for-distilbert.ipynb 10
learn = XCLearner(
    model=model, 
    args=args,
    data_collator=block.collator, 
    compute_metrics=metric,
)

# %% ../nbs/13-metadata-trie-for-distilbert.ipynb 13
meta_toks = block.train.dset.meta.hlk_meta.meta_info['input_ids']
meta_info = [o.indices.tolist() for o in tqdm(meta_lbl, total=meta_lbl.shape[0])]

trie = Trie.from_list(meta_toks, meta_info)

# %% ../nbs/13-metadata-trie-for-distilbert.ipynb 15
learn.tbs.trie = trie

# %% ../nbs/13-metadata-trie-for-distilbert.ipynb 16
learn.tbs.n_bm = learn.args.generation_num_beams = 20
