# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb.

# %% auto 0
__all__ = ['dump_dir', 'fname', 'mname', 'model', 'args', 'metric', 'learn', 'data_lbl', 'lbl_lbl', 'lbl_toks', 'lbl_info',
           'trie', 'meta_lbl', 'n_lbl', 'valid_meta_idx', 'meta_toks', 'meta_info', 'o', 'pred_fname']

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 2
import os, pandas as pd, warnings, torch, pickle, numpy as np
from tqdm.auto import tqdm
from scipy import stats

import xclib.utils.sparse as xs

from xcai.basics import *
from xcai.models.MMM00X import DBT007, DBT008
from xcai.transform import AugmentMetaInputIdsTfm

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 3
os.environ['WANDB_MODE'] = 'disabled'

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 4
dump_dir = '/home/aiscuser/scratch/Projects/xc_nlg/outputs/\
15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles'

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 11
fname = f'{dump_dir}/data/block.pkl'
with open(fname, 'rb') as f: block, test_dset = pickle.load(f)

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 14
mname = f'/home/aiscuser/scratch/Projects/XC-NLG/models/distilbert-base-uncased_RB33-NAR-3+8-2_(mapped)LF-AmazonTitles-1.3M/checkpoint-884000'
model = DBT007.from_pretrained(mname, tn_targ=10_000, ig_tok=0)

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 15
args = XCLearningArguments(
    output_dir=f'{dump_dir}/distilbert-base-uncased_RB33-NAR-3+8-2_(mapped)LF-AmazonTitles-1.3M',
    generation_length_penalty=1.5,
    per_device_eval_batch_size=32,
    evaluation_strategy='steps',
    label_names=['lbl2data_idx'],
)

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 16
metric = PrecRecl(test_dset.n_lbl, test_dset.data.data_lbl_filterer, prop=block.train.dset.data.data_lbl,
                  pk=10, rk=200, rep_pk=[1, 3, 5, 10], rep_rk=[2, 3, 10, 50, 100, 200])

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 18
learn = XCLearner(
    model=model, 
    args=args,
    data_collator=block.collator, 
    compute_metrics=metric,
)

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 20
data_lbl = block.train.dset.data.data_lbl
lbl_lbl = data_lbl.T.dot(data_lbl).tocsr()
lbl_lbl.setdiag(1)

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 21
lbl_toks = block.lbl_info['input_ids']
lbl_info = [o.indices.tolist() for o in lbl_lbl]

trie = Trie.from_list(lbl_toks, lbl_info)

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 23
meta_lbl = block.train.dset.meta.cat_meta.lbl_meta.T.tocsr()

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 24
n_lbl = meta_lbl.getnnz(axis=1)
valid_meta_idx = np.where(np.logical_and(n_lbl>1, n_lbl<100))[0]

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 25
meta_toks = [block.train.dset.meta.cat_meta.meta_info['input_ids'][i] for i in tqdm(valid_meta_idx)]
meta_info = [meta_lbl[i].indices.tolist() for i in tqdm(valid_meta_idx)]

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 26
trie.update(meta_toks, meta_info)

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 28
learn.tbs.trie = trie

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 30
learn.tbs.n_bm = learn.args.generation_num_beams = 20

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 31
o = learn.predict(test_dset)
print(o.metrics)

#display_metric(o.metrics)

# %% ../nbs/15-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding-on-amazon-titles.ipynb 34
pred_fname = f'{dump_dir}/distilbert-base-uncased_RB33-NAR-3+8-2_(mapped)LF-AmazonTitles-1.3M/checkpoint-884000/\
predictions/test_lbl_atrie-hlk_n-bm-20_n-smp-500_seed-50.pth'
os.makedirs(os.path.dirname(pred_fname), exist_ok=True)
torch.save(o, pred_fname)
