# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/17-ngame-training-pipeline-with-multitriplet-loss.ipynb.

# %% auto 0
__all__ = ['block', 'args', 'metric', 'bsz', 'model', 'learn']

# %% ../nbs/17-ngame-training-pipeline-with-multitriplet-loss.ipynb 4
import os,torch
from xcai.basics import *
from xcai.models.MMM00X import DBT009

# %% ../nbs/17-ngame-training-pipeline-with-multitriplet-loss.ipynb 6
os.environ['WANDB_PROJECT']='xc-nlg_17-ngame-training-pipeline-with-multitriplet-loss-3'

# %% ../nbs/17-ngame-training-pipeline-with-multitriplet-loss.ipynb 7
block = XCBlock.from_cfg('/home/aiscuser/scratch/datasets', 'data', valid_pct=0.001, tfm='xc', 
                         tokenizer='sentence-transformers/msmarco-distilbert-base-v4')

# %% ../nbs/17-ngame-training-pipeline-with-multitriplet-loss.ipynb 8
args = XCLearningArguments(
    output_dir='/home/aiscuser/outputs/17-ngame-training-pipeline-with-multitriplet-loss-3',
    logging_first_step=True,
    per_device_train_batch_size=1024,
    per_device_eval_batch_size=64,
    representation_num_beams=200,
    representation_accumulation_steps=100,
    save_strategy="steps",
    evaluation_strategy='steps',
    eval_steps=500,
    save_steps=500,
    save_total_limit=5,
    num_train_epochs=50,
    predict_with_representation=True,
    adam_epsilon=1e-6,
    warmup_steps=100,
    weight_decay=0.01,
    learning_rate=2e-5,
)

# %% ../nbs/17-ngame-training-pipeline-with-multitriplet-loss.ipynb 9
metric = PrecRecl(block.n_lbl, block.test.data_lbl_filterer, prop=block.train.dset.data.data_lbl,
                  pk=10, rk=200, rep_pk=[1, 3, 5, 10], rep_rk=[10, 100, 200])

# %% ../nbs/17-ngame-training-pipeline-with-multitriplet-loss.ipynb 11
bsz = max(args.per_device_train_batch_size, args.per_device_eval_batch_size)*torch.cuda.device_count()
model = DBT009.from_pretrained('sentence-transformers/msmarco-distilbert-base-v4', bsz=bsz, tn_targ=10_000, 
                               margin=0.3, tau=0.1, apply_softmax=True)

# %% ../nbs/17-ngame-training-pipeline-with-multitriplet-loss.ipynb 13
learn = XCLearner(
    model=model, 
    args=args,
    train_dataset=block.train.dset,
    eval_dataset=block.test.dset,
    data_collator=block.collator,
    compute_metrics=metric,
)

# %% ../nbs/17-ngame-training-pipeline-with-multitriplet-loss.ipynb 15
learn.train()
