# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/55-encoder-parallel-radga-inference-pipeline.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/55-encoder-parallel-radga-inference-pipeline.ipynb 3
import os,sys,torch,pickle,torch.multiprocessing as mp, pickle
from xcai.basics import *
from xcai.models.radga import RAD001

# %% ../nbs/55-encoder-parallel-radga-inference-pipeline.ipynb 5
os.environ['CUDA_VISIBLE_DEVICES'] = '12,13'
os.environ['WANDB_PROJECT']='xc-nlg_55-encoder-parallel-radga-inference-pipeline'
