# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/61-nar-unconstrained-generation.ipynb.

# %% auto 0
__all__ = ['pkl_dir', 'pkl_file', 'mdir', 'mname']

# %% ../nbs/61-nar-unconstrained-generation.ipynb 5
import os, torch, torch.nn.functional as F, pickle
from typing import Optional, Dict, Tuple, Union, List, Callable
from tqdm.auto import tqdm
from xcai.basics import *
from xcai.models.MMM0XX import DBT007

# %% ../nbs/61-nar-unconstrained-generation.ipynb 7
os.environ['CUDA_VISIBLE_DEVICES'] = '1'
os.environ['WANDB_PROJECT']='xc-nlg_61-nar-unconstrained-generation'

# %% ../nbs/61-nar-unconstrained-generation.ipynb 8
pkl_dir = '/home/scai/phd/aiz218323/scratch/datasets'
pkl_file = f'{pkl_dir}/processed/wikiseealso_data_distilbert-base-uncased_xcnlg_ngame.pkl'

with open(pkl_file, 'rb') as file: block = pickle.load(file)

# %% ../nbs/61-nar-unconstrained-generation.ipynb 19
mdir = '/home/scai/phd/aiz218323/scratch/outputs/20-nar-training-pipeline-for-distilbert-2-1'
mname = get_best_model(mdir)
