# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/63-ramen-ep-for-wikiseealso.ipynb.

# %% auto 0
__all__ = ['data_dir', 'pkl_dir', 'fname', 'args', 'metric', 'bsz', 'model', 'learn']

# %% ../nbs/63-ramen-ep-for-wikiseealso.ipynb 3
import os,torch, torch.multiprocessing as mp, pickle
from xcai.basics import *
from xcai.models.PPP0XX import DBT021

# %% ../nbs/63-ramen-ep-for-wikiseealso.ipynb 5
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'
os.environ['WANDB_PROJECT']='xc-nlg_xc-nlg_66-radga-dr-ep-for-wikiseealso'

# %% ../nbs/63-ramen-ep-for-wikiseealso.ipynb 8
data_dir = '/home/scai/phd/aiz218323/scratch/datasets'

# %% ../nbs/63-ramen-ep-for-wikiseealso.ipynb 9
pkl_dir = f'{data_dir}/processed'
fname = f'{pkl_dir}/wikiseealso_data-meta_distilbert-base-uncased_rm_ramen-cat.pkl'

# %% ../nbs/63-ramen-ep-for-wikiseealso.ipynb 11
with open(fname, 'rb') as file: block = pickle.load(file)

# %% ../nbs/63-ramen-ep-for-wikiseealso.ipynb 14
args = XCLearningArguments(
    output_dir='/home/scai/phd/aiz218323/scratch/outputs/63-ramen-ep-for-wikiseealso-2-3',
    logging_first_step=True,
    per_device_train_batch_size=800,
    per_device_eval_batch_size=800,
    representation_num_beams=200,
    representation_accumulation_steps=10,
    save_strategy="steps",
    evaluation_strategy="steps",
    eval_steps=1000,
    save_steps=1000,
    save_total_limit=5,
    num_train_epochs=300,
    predict_with_representation=True,
    adam_epsilon=1e-6,
    warmup_steps=100,
    weight_decay=0.01,
    learning_rate=2e-4,
    generation_num_beams=10,
    generation_length_penalty=1.5,
    predict_with_generation=True,
    representation_search_type='INDEX',
    group_by_cluster=True,
    num_clustering_warmup_epochs=10,
    num_cluster_update_epochs=5,
    num_cluster_size_update_epochs=25,
    clustering_type='EXPO',
    minimum_cluster_size=2,
    maximum_cluster_size=1600,
    output_concatenation_weight=1.0,
    metric_for_best_model='P@1',
    load_best_model_at_end=True,
    target_indices_key='plbl2data_idx',
    target_pointer_key='plbl2data_data2ptr',
    use_encoder_parallel=True,
    max_grad_norm=None,
    fp16=True,
    label_names=['cat2data_idx', 'cat2data_input_ids', 'cat2data_attention_mask',
                 'cat2lbl2data_idx', 'cat2lbl2data_input_ids', 'cat2lbl2data_attention_mask'],
    prune_metadata=True,
    num_metadata_prune_epochs=5,
    metadata_prune_batch_size=2048,
    num_metadata_prune_warmup_epochs=0,
    prune_metadata_names=['cat_meta']
)

# %% ../nbs/63-ramen-ep-for-wikiseealso.ipynb 15
metric = PrecRecl(block.n_lbl, block.test.data_lbl_filterer, prop=block.train.dset.data.data_lbl,
                  pk=10, rk=200, rep_pk=[1, 3, 5, 10], rep_rk=[10, 100, 200])

# %% ../nbs/63-ramen-ep-for-wikiseealso.ipynb 16
bsz = max(args.per_device_train_batch_size, args.per_device_eval_batch_size)*torch.cuda.device_count()

model = DBT021.from_pretrained('sentence-transformers/msmarco-distilbert-base-v4', tn_targ=1000, margin=0.3, tau=0.1, apply_softmax=True, n_negatives=10,
                           m_lw=[0.1, 0.1], meta_prefix='cat', use_encoder_parallel=True, task_repr_type='pool', meta_repr_type='pool')
model.init_dr_head()

# %% ../nbs/63-ramen-ep-for-wikiseealso.ipynb 17
learn = XCLearner(
    model=model,
    args=args,
    train_dataset=block.train.dset,
    eval_dataset=block.test.dset,
    data_collator=block.collator,
    compute_metrics=metric,
)

# %% ../nbs/63-ramen-ep-for-wikiseealso.ipynb 20
if __name__ == '__main__':
    mp.freeze_support()
    learn.train(resume_from_checkpoint=True)
