# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/87-oak-dr-ep-for-wikiseealso-with-additive-renee-embedding-and-generation.ipynb.

# %% auto 0
__all__ = ['pkl_dir', 'pkl_file', 'data_meta', 'args', 'bsz', 'model', 'valid_dset', 'metric', 'trie', 'learn']

# %% ../nbs/87-oak-dr-ep-for-wikiseealso-with-additive-renee-embedding-and-generation.ipynb 3
import os,torch, torch.multiprocessing as mp, pickle, numpy as np
from xcai.basics import *
from xcai.models.oak import OAK005
from xclib.utils.sparse import retain_topk

# %% ../nbs/87-oak-dr-ep-for-wikiseealso-with-additive-renee-embedding-and-generation.ipynb 5
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'
os.environ['WANDB_PROJECT']='xc-nlg_87-oak-dr-ep-for-wikiseealso-with-generation'

# %% ../nbs/87-oak-dr-ep-for-wikiseealso-with-additive-renee-embedding-and-generation.ipynb 7
pkl_dir = '/home/scai/phd/aiz218323/scratch/datasets/'
pkl_file = f'{pkl_dir}/processed/wikiseealso_data-metas_distilbert-base-uncased_rm_radga-cat-linker.pkl'

# %% ../nbs/87-oak-dr-ep-for-wikiseealso-with-additive-renee-embedding-and-generation.ipynb 8
with open(pkl_file, 'rb') as file: block = pickle.load(file)

# %% ../nbs/87-oak-dr-ep-for-wikiseealso-with-additive-renee-embedding-and-generation.ipynb 9
data_meta = retain_topk(block.train.dset.meta.lnk_meta.data_meta, k=5)
block.train.dset.meta.lnk_meta.curr_data_meta = data_meta
block.train.dset.meta.lnk_meta.data_meta = data_meta

data_meta = retain_topk(block.test.dset.meta.lnk_meta.data_meta, k=3)
block.test.dset.meta.lnk_meta.curr_data_meta = data_meta
block.test.dset.meta.lnk_meta.data_meta = data_meta

# %% ../nbs/87-oak-dr-ep-for-wikiseealso-with-additive-renee-embedding-and-generation.ipynb 11
args = XCLearningArguments(
    output_dir='/home/scai/phd/aiz218323/scratch/outputs/87-oak-dr-ep-for-wikiseealso-with-additive-renee-embedding-and-generation-1-0',
    logging_first_step=True,
    per_device_train_batch_size=800,
    per_device_eval_batch_size=800,
    representation_num_beams=200,
    representation_accumulation_steps=10,
    save_strategy="steps",
    evaluation_strategy="steps",
    eval_steps=5000,
    save_steps=5000,
    save_total_limit=5,
    num_train_epochs=300,
    predict_with_representation=True,
    adam_epsilon=1e-6,
    warmup_steps=100,
    weight_decay=0.01,
    learning_rate=2e-4,
    generation_num_beams=10,
    generation_length_penalty=1.5,
    predict_with_generation=True,
    representation_search_type='BRUTEFORCE',
    
    output_representation_attribute='data_fused_repr',
    label_representation_attribute='data_repr',
    metadata_representation_attribute='data_repr',
    data_augmentation_attribute='data_repr',
    representation_attribute='data_fused_repr',
    clustering_representation_attribute='data_fused_repr',
    
    group_by_cluster=False,
    num_clustering_warmup_epochs=10,
    num_cluster_update_epochs=5,
    num_cluster_size_update_epochs=25,
    use_data_metadata_for_clustering=True,
    clustering_type='EXPO',
    minimum_cluster_size=2,
    maximum_cluster_size=1600,

    metric_for_best_model='P@1',
    load_best_model_at_end=True,
    target_indices_key='plbl2data_idx',
    target_pointer_key='plbl2data_data2ptr',
    
    use_distributional_representation=False,
    use_encoder_parallel=True,
    max_grad_norm=None, 
    fp16=True,
    
    label_names=['lnk2data_idx', 'lnk2data_input_ids', 'lnk2data_attention_mask'],
    
    prune_metadata=False,
    num_metadata_prune_warmup_epochs=10,
    num_metadata_prune_epochs=5,
    metadata_prune_batch_size=2048,
    prune_metadata_names=['lnk_meta'],
    use_data_metadata_for_pruning=True,

    predict_with_augmentation=False,
    use_augmentation_index_representation=True,
    
    data_aug_meta_name='lnk',
    augmentation_num_beams=3,
    data_aug_prefix='lnk',
    use_label_metadata=False,
    
    data_meta_batch_size=2048,
    augment_metadata=False,
    num_metadata_augment_warmup_epochs=10,
    num_metadata_augment_epochs=5,
)

# %% ../nbs/87-oak-dr-ep-for-wikiseealso-with-additive-renee-embedding-and-generation.ipynb 13
bsz = max(args.per_device_train_batch_size, args.per_device_eval_batch_size)*torch.cuda.device_count()

model = OAK005.from_pretrained('sentence-transformers/msmarco-distilbert-base-v4', batch_size=bsz, num_batch_labels=5000, 
                               margin=0.3, num_negatives=10, tau=0.1, apply_softmax=True,
                               
                               data_aug_meta_prefix='lnk2data', lbl2data_aug_meta_prefix=None, 
                               data_pred_meta_prefix=None, lbl2data_pred_meta_prefix=None,
                               
                               num_metadata=block.train.dset.meta['lnk_meta'].n_meta, resize_length=5000,
                               
                               calib_margin=0.05, calib_num_negatives=10, calib_tau=0.1, calib_apply_softmax=False, 
                               calib_loss_weight=0.1, use_calib_loss=False,
                               
                               use_query_loss=False,

                               meta_loss_weight=0.0, 
                               
                               fusion_loss_weight=0.1, use_fusion_loss=False,

                               ignore_token=0, gen_loss_weight=1.0, use_gen_loss=True,
                               
                               use_encoder_parallel=False)

model.init_generation_head()

model.freeze()
model.unfreeze_head()

model.use_representation = False

# model.init_retrieval_head()
# model.init_cross_head()
# model.init_meta_embeddings()
# model.encoder.set_pretrained_meta_embeddings(torch.zeros(656086, 768))
# model.encoder.freeze_pretrained_meta_embeddings()

# %% ../nbs/87-oak-dr-ep-for-wikiseealso-with-additive-renee-embedding-and-generation.ipynb 15
valid_dset = block.test.sample(n=2000)
metric = PrecRecl(block.n_lbl, valid_dset.data_lbl_filterer, prop=block.train.dset.data.data_lbl,
                  pk=10, rk=200, rep_pk=[1, 3, 5, 10], rep_rk=[10, 100, 200])

# %% ../nbs/87-oak-dr-ep-for-wikiseealso-with-additive-renee-embedding-and-generation.ipynb 16
trie = XCTrie.from_block(block)

# %% ../nbs/87-oak-dr-ep-for-wikiseealso-with-additive-renee-embedding-and-generation.ipynb 17
learn = XCLearner(
    model=model, 
    args=args,
    trie=trie,
    train_dataset=block.train.dset,
    eval_dataset=valid_dset.dset,
    data_collator=block.collator,
    compute_metrics=metric,
)

# %% ../nbs/87-oak-dr-ep-for-wikiseealso-with-additive-renee-embedding-and-generation.ipynb 19
if __name__ == '__main__':
    mp.freeze_support()
    learn.train()
    
