# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/xc_nlg',
                'doc_host': 'https://suchith720.github.io',
                'git_url': 'https://github.com/suchith720/xc_nlg',
                'lib_path': 'xc_nlg'},
  'syms': { 'xc_nlg.00-nar-trie-inference-benchmarking': {},
            'xc_nlg.02-nar-training-pipeline': {},
            'xc_nlg.03-NGAME-training-pipeline': {},
            'xc_nlg.04-metadata-augmented-trie-for-distilbert': {},
            'xc_nlg.05-metadata-augmented-input-and-trie-for-distilbert': {},
            'xc_nlg.06-metadata-augmented-input-and-trie-for-distilbert-n_bm-50': {},
            'xc_nlg.07-metadata-augmented-input-and-trie-for-distilbert-with-thresholding': {},
            'xc_nlg.09-faster-trie-implementation': {},
            'xc_nlg.10-metadata-label-matrix-augmented-input-and-trie-for-distilbert-with-thresholding': {},
            'xc_nlg.11-label-matrix-augmented-input-trie-for-distilbert': {},
            'xc_nlg.12-metadata-label-matrix-augmented-input-trie-for-distilbert': {},
            'xc_nlg.13-metadata-trie-for-distilbert': {}}}
